### ISSUE TITLE
Design question about Math.max for a single element

### ISSUE THREAD

**Issue by seanpoulter** [sampepose/ng-flot#1]
I realize it's been years since you've wrote this, but I've been curious about why you chose to use `Math.max` on the single X and Y coordinate in [`data.setMax`](https://github.com/sampepose/ng-flot/blob/addf89afca24c07d147edbba8aa0cbd4e2800ef7/ng-flot-0.1.2.js#L111). Do you remember why you went with that?

It seems like it is being used to cast the value to a number, and the same behaviour as `max = Number(coordinateValue)` since `Math.max` will return `NaN` when a value can't be converted to a number <sup>1</sup>.

<sup>1</sup>: [MDN Math.max API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max)

**Comment by sampepose** [comment]
It's a bug. There's no need to use `Math.max`, a simple assignment would work. There are much better ways of writing this code :-)

I'd be surprised if this library still works tbh.
